# Generated by Django 5.0.4 on 2024-04-23 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashapp', '0002_remove_qp_course_remove_videos_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sem_choice', models.CharField(choices=[('sem1', 'Sem1'), ('sem2', 'Sem2'), ('sem3', 'Sem3'), ('sem4', 'Sem4'), ('sem5', 'Sem5'), ('sem6', 'Sem6')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sub_id', models.CharField(max_length=10, unique=True)),
                ('sub_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Qp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('filepath', models.FileField(upload_to='pdfs/')),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.sem')),
            ],
        ),
        migrations.CreateModel(
            name='Studymaterials',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('filepath', models.FileField(upload_to='pdfs/')),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.course')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.sem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('filepath', models.FileField(upload_to='video/')),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.course')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashapp.sem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
