# Generated by Django 5.0.4 on 2024-04-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studymaterials',
            name='course',
        ),
        migrations.RemoveField(
            model_name='qp',
            name='course',
        ),
        migrations.RemoveField(
            model_name='qp',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='qp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='studymaterials',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='studymaterials',
            name='user',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Qp',
        ),
        migrations.DeleteModel(
            name='Sem',
        ),
        migrations.DeleteModel(
            name='Studymaterials',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
